### ISSUE TITLE
Some features request for miui

### ISSUE THREAD

**Issue by exodius48** [rarnu/root-tools#39]
Could you unlock paid china theme on global rom?
Also prevent downloaded theme deleted after imported? So we can save mtz file

Also could you add bypass region for music? I can't play music online, i always need china vpn server in order to play music. And some music can't be downloaded , need premium pack song.

**Comment by rarnu** [comment]
Could you unlock paid china theme on global rom?
A: Yes, I wil try.
Also prevent downloaded theme deleted after imported? So we can save mtz file
A: OK and it will be a new switcher.

Also could you add bypass region for music? I can't play music online, i always need china vpn server in order to play music. And some music can't be downloaded , need premium pack song.
A: It's a copyright issue and crack on it is not a good idea. But I still willing to try...

**Comment by exodius48** [comment]
If you talk about copyright, All paid china themes are copyright too, then why you make theme crack in this module? Haha...
Ok, hope good news from you. This is needed module right now because MiThemes abandoned since MIUI 6 released.
